# This is a Docker Compose file for setting up the morphic-stack environment.

name: morphic-stack
services:
  morphic:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile
    command: bun dev -H 0.0.0.0 # Use `bun dev` to listen on default interface
    ports:
      - '3001:3000' # Maps port 3001 on the host to port 3000 in the container.
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
