name: morphic
services:
  morphic:
    container_name: morphic
    env_file: stack.env
    build:
      context: .
      dockerfile: Dockerfile
    command: bun dev -H 0.0.0.0
    restart: always
    ports:
      - '10003:3000'
